# Generated by Django 4.2 on 2025-12-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecontent',
            name='about_paragraph1',
            field=models.TextField(default='Short paragraph describing who you are, your degree, and what you are looking for.'),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='about_paragraph2',
            field=models.TextField(default='Another short paragraph about your interests, learning mindset, and goals.'),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='about_title',
            field=models.CharField(default='About Me', max_length=200),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='availability',
            field=models.CharField(default='Open to Work', max_length=50),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='degree',
            field=models.CharField(default='B.Tech in Information Technology', max_length=100),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='email',
            field=models.EmailField(default='yourmail@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='experience',
            field=models.CharField(default='Fresher / Internship Experience', max_length=100),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='location',
            field=models.CharField(default='Kozhikode, Kerala, India', max_length=100),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='phone',
            field=models.CharField(default='+91 XXXXXXXXXX', max_length=20),
        ),
    ]
