# Generated by Django 4.2 on 2025-12-16 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_homecontent_about_paragraph1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('home_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='backend.homecontent')),
            ],
        ),
    ]
