# Generated by Django 4.2 on 2025-12-31 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecontent',
            name='resume',
            field=models.FileField(blank=True, help_text='Upload your resume PDF', null=True, upload_to='resumes/'),
        ),
    ]
