# Generated by Django 4.2 on 2026-01-06 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_homecontent_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('home_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='backend.homecontent')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('year_range', models.CharField(max_length=50)),
                ('degree_level', models.CharField(max_length=100)),
                ('home_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='backend.homecontent')),
            ],
        ),
    ]
