# Generated by Django 4.2 on 2026-01-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_experience_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('points', models.TextField(help_text='Write one point per line')),
                ('file', models.FileField(blank=True, null=True, upload_to='projects/')),
            ],
        ),
    ]
