# Generated by Django 4.2 on 2026-01-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='points',
        ),
        migrations.AddField(
            model_name='project',
            name='tech_stack',
            field=models.CharField(blank=True, help_text='Technologies used in this project', max_length=200),
        ),
    ]
