# Generated by Django 4.2 on 2025-12-16 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('overview', models.TextField()),
                ('highlights', models.JSONField(default=list)),
                ('technical_implementation', models.TextField()),
                ('quote', models.TextField()),
                ('author_name', models.CharField(max_length=100)),
                ('author_role', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('category', models.CharField(max_length=100)),
                ('client', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=50)),
                ('technologies', models.CharField(max_length=200)),
                ('live_url', models.URLField(blank=True)),
                ('tags', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('tagline', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('headline', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=50)),
                ('delivery_time', models.CharField(max_length=50)),
                ('revisions', models.CharField(max_length=50)),
                ('support', models.CharField(max_length=50)),
                ('badge', models.CharField(default='Premium Service', max_length=50)),
                ('tech_stack', models.JSONField(default=list)),
                ('testimonial', models.TextField()),
                ('client_name', models.CharField(max_length=100)),
                ('client_title', models.CharField(max_length=100)),
                ('rating', models.IntegerField(default=5)),
                ('tech_categories', models.JSONField(default=list)),
            ],
        ),
    ]
